[dev]
framework = "#static"
command = "npx @11ty/eleventy --input=src --quiet --watch"

[build]
command = "npx @11ty/eleventy --input=src"
publish = "dist"

[[edge_functions]]
function = "closest-parks"
path = "/"